// Existing content of the script.js file up to line 371...  
// Updated changes to line 372 and line 378  
const room = await DB.createRoom(type === 'dm' ? '1v1' : 'gc', [targetProfile.id]);  
// Existing content of the script.js file from line 373 to line 377...
const roomData = {  
    // Other properties...  
    type: type === 'dm' ? '1v1' : 'gc',  
    // Other properties...  
};
// Remaining content of the script.js file...